### ISSUE TITLE
CMake (3.12.1)

### ISSUE THREAD

**Issue by chuckatkins** [openhpc/ohpc#845] opened 2018-09-06 17:54 UTC
3.12 addressed an important bug introduced into 3.11 that causes the Intel C compiler to not be able to properly use -std=gnu11 and instead always use -std=c11, which forces ANSI C compatibility and breaks POSIX functionality.

**Comment by crbaird** [comment] 2018-09-09 22:48
duplicate of #769

**Closed by crbaird** 2018-09-09 22:48 UTC
Labels: component, duplicate
