### ISSUE TITLE
unable to compile lustre-client-ohpc

### ISSUE THREAD

**Issue by arm2arm** [openhpc/ohpc#1394] opened 2021-11-19 15:39 UTC
Hi I am deploying now ohpc+slurm+warewulf on RokyLinux8.5, so far so good.
The  lustre-client-ohpc-2.12.7-4.2.ohpc.2.4 is coming with the previous kernel. After upgrade of 8.4->8.5 I was trying to compile with following:
* rpmbuild --rebuild lustre-client-ohpc-2.12.7-4.2.ohpc.2.4.src.rpm
```
[root@nnewl1 ~]# rpmbuild --rebuild lustre-client-ohpc-2.12.7-4.2.ohpc.2.4.src.rpm
configure: error: Kernel source  could not be found.
error: Bad exit status from /var/tmp/rpm-tmp.fkou7e (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.fkou7e (%build)
```
The kernel-dev is installed, zfs-dkms was compiling without problems.

Then, getting the lustre source from the official Lustrefs repo works without problems:
```
wget https://downloads.whamcloud.com/public/lustre/latest-release/el8/client/SRPMS/lustre-2.12.7-1.src.rpm
rpmbuild --rebuild --without servers  --with lnet-dlc --with lustre-utils lustre-2.12.7-1.src.rpm
```

PS
BTW there are some issues with gcc9 with the lustre, to compile it, one should use the gcc8 which is natively coming with RockyLinux 8.5

**Comment by adrianreber** [comment] 2022-12-05 10:11
I am closing this as 2.6 is the current release and we were able to compile the latest version on RHEL and LEAP.

**Closed as completed by adrianreber** 2022-12-05 10:11 UTC

**Comment by martin-g** [comment] 2022-12-05 12:29
https://github.com/openhpc/ohpc/blob/2.x/.cirrus.yml#L3 - should this exclusion be removed then ?

**Comment by adrianreber** [comment] 2022-12-05 12:51
> https://github.com/openhpc/ohpc/blob/2.x/.cirrus.yml#L3 - should this exclusion be removed then ?

No, the problem is that we cannot automatically download the lustre tar archive. We have to download the SRPM from upstream, unpack the tar archive from the SRPM and then use that.

We could have a way to have a hook for certain packages which need special source retrieval, but currently we do not have it.
