### ISSUE TITLE
Can not install ohpc-gnu12-runtimes on Rocky 8

### ISSUE THREAD

**Issue by devilkingsatan666** [openhpc/ohpc#1644] opened 2023-01-01 06:20 UTC
After issuing:
   dnf install ohpc-gnu12-runtimes.x86_64
I got the following error:
Error: 
  Problem: conflicting requests
     - nothing provides singularity needed by ohpc-gnu12-runtimes-2.6-7.1.ohpc.2.6.x86_64

Interestingly, I have apptainer version 1.1.4-2.el8 installed on my system.

No idea what's going wrong.

Best,
Wu-Cheng Chiang

**Comment by adrianreber** [comment] 2023-01-04 08:33
The problem is that the package `apptainer` from EPEL used to provide the dependency `singularity` although it is not really singularity. EPEL decided to remove this packaging error https://pagure.io/epel/issue/214. So now, nothing provides `singularity` in EPEL.

Either EPEL needs to introduce the real `singularity` package or OpenHPC needs to do a small update to replace the require on `singularity` with `apptainer`.

**Comment by devilkingsatan666** [comment] 2023-01-04 08:54
EPEL has singularity-ce-3.10.4-1 available for installlation. Which one will the community choose to be the default one?

Best,
Wu-Cheng Chiang

**Comment by sjpb** [comment] 2023-01-04 11:38
This is probably way off base but is `singularity-ohpc` suitable to be marked as `provides singularity`? I guess the use of environment modules by that package means maybe not?

---

A temporary fix seems to be to do:
```
dnf install -y https://github.com/apptainer/apptainer/releases/download/v1.1.3/apptainer-1.1.3-1.x86_64.rpm
```

**Comment by sjpb** [comment] 2023-01-04 11:39
Also - the title of this suggests the problem is narrower than it is - `ohpc-base-compute` also depends on `singularity` in v2.6, which means openhpc can't currently be used to create compute nodes without a workaround.

**Comment by adrianreber** [comment] 2023-01-04 11:46
> This is probably way off base but is `singularity-ohpc` suitable to be marked as `provides singularity`? I guess the use of environment modules by that package means maybe not?

We decided to not ship a copy of singularity because EPEL and LEAP do already ship one. The apptainer/singularity situation seems to be complicated and I do not understand what is happening.

There are a couple of fixes possible. I would just change the meta package to require apptainer on RHEL based clones and it should be fixed.

> A temporary fix seems to be to do:
> 
> ```
> dnf install -y https://github.com/apptainer/apptainer/releases/download/v1.1.3/apptainer-1.1.3-1.x86_64.rpm
> ```

Thanks.

**Closed as completed** 2023-01-04 14:49 UTC

**Comment by koomie** [comment] 2023-02-08 15:05
Tests passing in CI with latest build of meta-packages.
